
services:
  api:
    container_name: "kamalla_API"
    build: .
    command: sh -c "bunx prisma migrate dev --name docker-migrate && bun run --bun start:dev"
    environment:
      PORT: 3333
      DATABASE_URL: "postgresql://user:pass@database:5432/kamalla?schema=public"
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    depends_on:
      - database
    restart: always 
    networks:
      - public_network
      - private_network

  database:
    image: postgres:16
    container_name: "kamalla_DB"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: kamalla
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - private_network


volumes:
  postgres_data:

networks:
  public_network:
    driver: bridge
  private_network:
    driver: bridge